
import java.awt.Color;
import java.awt.Graphics;


public class Convex extends javax.swing.JPanel {

    /**
     * Creates new form convex
     */
    int n = 10;
    Point[] points;
    TwoPoint[] boundaryPair;
    int countBoundary;

    public Convex(Point[] points, TwoPoint[] TwoPoints, int bC) {
        this.points = points;
        this.boundaryPair = TwoPoints;
        countBoundary = bC;
        initComponents();
    }

    public void paintComponent(Graphics page) {
        int radius = 10;
        for (int i = 0; i < points.length; i++) {
            page.setColor(Color.BLACK);
            page.drawOval(points[i].x - radius / 2, points[i].y - radius / 2, 10, 10);
            page.setColor(Color.red);
            page.fillOval(points[i].x - radius / 2, points[i].y - radius / 2, 10, 10);
        }
        page.setColor(Color.magenta);
        for (int i = 0; i < countBoundary; i++) {
            page.drawLine(boundaryPair[i].a.x,boundaryPair[i].a.y,boundaryPair[i].b.x,boundaryPair[i].b.y);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
