/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package closestpair_convexhull;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author CSC318
 */
public class convex extends javax.swing.JPanel {

    /**
     * Creates new form convex
     */
    int n = 10;
    int[][] points;
    int[] cP;
    int[][] boundaryPair;
    int countBoundary;

    public convex(int[][] p, int[] cP, int[][] bP, int bC) {
        this.points = p;
        this.cP = cP;
        this.boundaryPair = bP;
        countBoundary = bC;
        initComponents();
    }

    public void paintComponent(Graphics page) {
        int radius = 10;
        for (int i = 0; i < points.length; i++) {
            page.setColor(Color.BLACK);
            page.drawOval(points[i][0] - radius / 2, points[i][1] - radius / 2, 10, 10);
            page.setColor(Color.red);
            page.fillOval(points[i][0] - radius / 2, points[i][1] - radius / 2, 10, 10);
        }
        page.setColor(Color.magenta);
        for (int i = 0; i < countBoundary; i++) {
            page.drawLine(points[boundaryPair[i][0]][0], points[boundaryPair[i][0]][1], points[boundaryPair[i][1]][0], points[boundaryPair[i][1]][1]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
